logging.level.org.zalando.logbook: TRACE

spring:
  sql:
    init.mode: always
  # в jdbc-url укажите, что данные нужно сохранять в файл
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver

filmorate:
  storage:
    film: filmDbStorage #filmDbStorage, inMemoryFilmStorage
    user: userDbStorage #userDbStorage, inMemoryUserStorage
    mpa: mpaDbStorage #mpaDbStorage, inMemoryMpaStorage
    genre: genreDbStorage #genreDbStorage, inMemoryGenreStorage